### ISSUE TITLE
   ValueError: Found two metrics with the same name: discriminator_acc

### ISSUE THREAD

**Issue by zhaoguangyuan123** [Changchun-Yang/LoftGAN#1]
I tried preparing data and run with python train.py.
However i got error `'   ` ValueError: Found two metrics with the same name: discriminator_acc'``

I guess it result out from line 
`    discriminator_train.compile(rmsprop, ['binary_crossentropy'] * 3, ['acc']*3 )
`
Could you kindly let me know how to solve this, or please let me know the edition of packages we can use to reproduce

Best

**Comment by Changchun-Yang** [comment]
Hi,
Sorry I haven't encountered this error.
But according to experience, it should be the reason of mismatched tensorflow or keras. 
So I uploaded the "requirements.txt" on the master branch.
Hope it helps you.
By the way, when there are multiple branches or multiple losses, pytorch will be more convenient than tensorflow.
Good luck.

**Comment by zhaoguangyuan123** [comment]
Thank you changchun.
I will try it.

Thank you for the recommendation on torch. I am actually also more used to torch and I will try it if possible. 

Happy new year!
